// <auto-generated />
using System;
using Lequ.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lequ.Repository.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211031025436_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlogCategory", b =>
                {
                    b.Property<int>("BlogsID")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesID")
                        .HasColumnType("int");

                    b.HasKey("BlogsID", "CategoriesID");

                    b.HasIndex("CategoriesID");

                    b.ToTable("BlogCategory");
                });

            modelBuilder.Entity("Lequ.Model.Models.About", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Details2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("Lequ.Model.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6349),
                            Password = "admin",
                            Status = true,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("About")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            About = "Coder",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6478),
                            Name = "Lequ.CO",
                            Status = true
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Blog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorID = 1,
                            Content = "test content 0",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6534),
                            Status = true,
                            Title = "test title 0"
                        },
                        new
                        {
                            ID = 2,
                            AuthorID = 1,
                            Content = "test content 1",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6538),
                            Status = true,
                            Title = "test title 1"
                        },
                        new
                        {
                            ID = 3,
                            AuthorID = 1,
                            Content = "test content 2",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6546),
                            Status = true,
                            Title = "test title 2"
                        },
                        new
                        {
                            ID = 4,
                            AuthorID = 1,
                            Content = "test content 3",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6549),
                            Status = true,
                            Title = "test title 3"
                        },
                        new
                        {
                            ID = 5,
                            AuthorID = 1,
                            Content = "test content 4",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6551),
                            Status = true,
                            Title = "test title 4"
                        },
                        new
                        {
                            ID = 6,
                            AuthorID = 1,
                            Content = "test content 5",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6555),
                            Status = true,
                            Title = "test title 5"
                        },
                        new
                        {
                            ID = 7,
                            AuthorID = 1,
                            Content = "test content 6",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6557),
                            Status = true,
                            Title = "test title 6"
                        },
                        new
                        {
                            ID = 8,
                            AuthorID = 1,
                            Content = "test content 7",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6559),
                            Status = true,
                            Title = "test title 7"
                        },
                        new
                        {
                            ID = 9,
                            AuthorID = 1,
                            Content = "test content 8",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6561),
                            Status = true,
                            Title = "test title 8"
                        },
                        new
                        {
                            ID = 10,
                            AuthorID = 1,
                            Content = "test content 9",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6564),
                            Status = true,
                            Title = "test title 9"
                        },
                        new
                        {
                            ID = 11,
                            AuthorID = 1,
                            Content = "test content 10",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6566),
                            Status = true,
                            Title = "test title 10"
                        },
                        new
                        {
                            ID = 12,
                            AuthorID = 1,
                            Content = "test content 11",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6568),
                            Status = true,
                            Title = "test title 11"
                        },
                        new
                        {
                            ID = 13,
                            AuthorID = 1,
                            Content = "test content 12",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6570),
                            Status = true,
                            Title = "test title 12"
                        },
                        new
                        {
                            ID = 14,
                            AuthorID = 1,
                            Content = "test content 13",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6572),
                            Status = true,
                            Title = "test title 13"
                        },
                        new
                        {
                            ID = 15,
                            AuthorID = 1,
                            Content = "test content 14",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6574),
                            Status = true,
                            Title = "test title 14"
                        },
                        new
                        {
                            ID = 16,
                            AuthorID = 1,
                            Content = "test content 15",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6576),
                            Status = true,
                            Title = "test title 15"
                        },
                        new
                        {
                            ID = 17,
                            AuthorID = 1,
                            Content = "test content 16",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6578),
                            Status = true,
                            Title = "test title 16"
                        },
                        new
                        {
                            ID = 18,
                            AuthorID = 1,
                            Content = "test content 17",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6581),
                            Status = true,
                            Title = "test title 17"
                        },
                        new
                        {
                            ID = 19,
                            AuthorID = 1,
                            Content = "test content 18",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6583),
                            Status = true,
                            Title = "test title 18"
                        },
                        new
                        {
                            ID = 20,
                            AuthorID = 1,
                            Content = "test content 19",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6585),
                            Status = true,
                            Title = "test title 19"
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 10, 54, 35, 913, DateTimeKind.Local).AddTicks(6493),
                            Name = "C#",
                            Status = true
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("BlogID");

                    b.HasIndex("ParentID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Lequ.Model.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SurName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BlogCategory", b =>
                {
                    b.HasOne("Lequ.Model.Models.Blog", null)
                        .WithMany()
                        .HasForeignKey("BlogsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lequ.Model.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lequ.Model.Models.Blog", b =>
                {
                    b.HasOne("Lequ.Model.Models.Author", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Lequ.Model.Models.Category", b =>
                {
                    b.HasOne("Lequ.Model.Models.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lequ.Model.Models.Comment", b =>
                {
                    b.HasOne("Lequ.Model.Models.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lequ.Model.Models.Comment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID");

                    b.Navigation("Blog");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lequ.Model.Models.Author", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Lequ.Model.Models.Blog", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
