// <auto-generated />
using System;
using Lequ.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lequ.Repository.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lequ.Model.Models.About", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Details2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Image1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("Lequ.Model.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3060),
                            Password = "admin",
                            Status = true,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("About")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            About = "Coder",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3170),
                            Name = "Lequ.CO",
                            Status = true
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Blog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "test content 0",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3227),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 0"
                        },
                        new
                        {
                            ID = 2,
                            Content = "test content 1",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3236),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 1"
                        },
                        new
                        {
                            ID = 3,
                            Content = "test content 2",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3240),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 2"
                        },
                        new
                        {
                            ID = 4,
                            Content = "test content 3",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3245),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 3"
                        },
                        new
                        {
                            ID = 5,
                            Content = "test content 4",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3248),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 4"
                        },
                        new
                        {
                            ID = 6,
                            Content = "test content 5",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3260),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 5"
                        },
                        new
                        {
                            ID = 7,
                            Content = "test content 6",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3263),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 6"
                        },
                        new
                        {
                            ID = 8,
                            Content = "test content 7",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3266),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 7"
                        },
                        new
                        {
                            ID = 9,
                            Content = "test content 8",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3269),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 8"
                        },
                        new
                        {
                            ID = 10,
                            Content = "test content 9",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3274),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 9"
                        },
                        new
                        {
                            ID = 11,
                            Content = "test content 10",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3278),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 10"
                        },
                        new
                        {
                            ID = 12,
                            Content = "test content 11",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3281),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 11"
                        },
                        new
                        {
                            ID = 13,
                            Content = "test content 12",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3284),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 12"
                        },
                        new
                        {
                            ID = 14,
                            Content = "test content 13",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3287),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 13"
                        },
                        new
                        {
                            ID = 15,
                            Content = "test content 14",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3291),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 14"
                        },
                        new
                        {
                            ID = 16,
                            Content = "test content 15",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3294),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 15"
                        },
                        new
                        {
                            ID = 17,
                            Content = "test content 16",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3297),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 16"
                        },
                        new
                        {
                            ID = 18,
                            Content = "test content 17",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3302),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 17"
                        },
                        new
                        {
                            ID = 19,
                            Content = "test content 18",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3305),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 18"
                        },
                        new
                        {
                            ID = 20,
                            Content = "test content 19",
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3308),
                            Image = "/Front/images/img_1.jpg",
                            Status = true,
                            Title = "test title 19"
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.BlogCategory", b =>
                {
                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BlogID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("BlogCategory");

                    b.HasData(
                        new
                        {
                            BlogID = 1,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3230),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 1,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3233),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 2,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3237),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 2,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3238),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 3,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3241),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 3,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3243),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 4,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3245),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 4,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3246),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 5,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3249),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 5,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3257),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 6,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3260),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 6,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3261),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 7,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3264),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 7,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3264),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 8,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3267),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 8,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3268),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 9,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3270),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 9,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3272),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 10,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3275),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 10,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3276),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 11,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3278),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 11,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3279),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 12,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3282),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 12,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3282),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 13,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3285),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 13,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3285),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 14,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3288),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 14,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3289),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 15,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3291),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 15,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3292),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 16,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3295),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 16,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3295),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 17,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3298),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 17,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3299),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 18,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3303),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 18,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3303),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 19,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3306),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 19,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3306),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 20,
                            CategoryID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3309),
                            ID = 0,
                            Status = true
                        },
                        new
                        {
                            BlogID = 20,
                            CategoryID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3310),
                            ID = 0,
                            Status = true
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3189),
                            Name = "C#",
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            CreateBy = 1,
                            CreateDate = new DateTime(2021, 10, 31, 22, 37, 26, 264, DateTimeKind.Local).AddTicks(3190),
                            Name = "C++",
                            Status = true
                        });
                });

            modelBuilder.Entity("Lequ.Model.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BlogID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("BlogID");

                    b.HasIndex("ParentID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Lequ.Model.Models.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Subject")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SurName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Lequ.Model.Models.Blog", b =>
                {
                    b.HasOne("Lequ.Model.Models.Author", null)
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorID");
                });

            modelBuilder.Entity("Lequ.Model.Models.BlogCategory", b =>
                {
                    b.HasOne("Lequ.Model.Models.Blog", "Blog")
                        .WithMany("BlogCategories")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lequ.Model.Models.Category", "Category")
                        .WithMany("BlogCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lequ.Model.Models.Category", b =>
                {
                    b.HasOne("Lequ.Model.Models.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lequ.Model.Models.Comment", b =>
                {
                    b.HasOne("Lequ.Model.Models.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lequ.Model.Models.Comment", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID");

                    b.Navigation("Blog");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lequ.Model.Models.Author", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("Lequ.Model.Models.Blog", b =>
                {
                    b.Navigation("BlogCategories");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Lequ.Model.Models.Category", b =>
                {
                    b.Navigation("BlogCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
